version : '3'

services:
  mysql:
    image: mysql:5.7
    container_name: fixme-mysql
    environment:
      MYSQL_USER: swingy
      MYSQL_PASSWORD: swingypass
      MYSQL_ROOT_PASSWORD: Rootroot3
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
